# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'


pod 'BoxView'

target 'ServerTarget' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for ServerTarget

end

target 'STransportLayer' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for STransportLayer

end
